<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;</TargetFrameworks>
		<Version>3.4.2.0</Version>
		<AssemblyVersion>3.4.2.0</AssemblyVersion>
		<FileVersion>3.4.2.0</FileVersion>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="echo copy $(TargetPath) C:\Users\scott.TOWEL42\Dropbox\home\bin\EmbyServer\programdata\plugins\" />
		<Exec Command="copy $(TargetPath) C:\Users\scott.TOWEL42\Dropbox\home\bin\EmbyServer\programdata\plugins\" />
	</Target>

	<ItemGroup>
		<None Remove="commandline.txt" />
		<None Remove="Configuration\moviePage.js" />
		<None Remove="Configuration\movieTextPage.js" />
		<None Remove="Configuration\showOverview.js" />
		<None Remove="Configuration\StatisticsConfigPage.html" />
		<None Remove="Configuration\StatisticsConfigPage.js" />
		<None Remove="Configuration\userBased.js" />
		<None Remove="Images\statistics-thumb.png" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Configuration\moviePage.js" />
		<EmbeddedResource Include="Configuration\movieTextPage.js" />
		<EmbeddedResource Include="Configuration\showOverview.js" />
		<EmbeddedResource Include="Configuration\StatisticsConfigPage.html" />
		<EmbeddedResource Include="Configuration\StatisticsConfigPage.js" />
		<EmbeddedResource Include="Configuration\movieTextPage.html" />
		<EmbeddedResource Include="Configuration\moviePage.html" />
		<EmbeddedResource Include="Configuration\showOverview.html" />
		<EmbeddedResource Include="Configuration\userBased.html" />
		<EmbeddedResource Include="Configuration\userBased.js" />
		<EmbeddedResource Include="Images\statistics-thumb.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediaBrowser.Server.Core" Version="4.8.11" />
		<PackageReference Include="System.Memory" Version="4.5.5" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Models\Configuration\" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>BuildDate</_Parameter1>
			<_Parameter2>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ssK"))</_Parameter2>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
