<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;</TargetFrameworks>
		<Version>3.4.2.1</Version>
		<AssemblyVersion>3.4.2.1</AssemblyVersion>
		<FileVersion>3.4.2.1</FileVersion>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="echo killing current EmbyServer" />
        <Exec Command="taskkill /IM EmbyServer.exe /F" IgnoreExitCode="true" />
        <Exec Command="taskkill /IM embytray.exe /F" IgnoreExitCode="true" />
		<Exec Command="echo copy $(TargetPath) C:\Users\scott.TOWEL42\Dropbox\home\bin\EmbyServer\programdata\plugins\" />
		<Exec Command="copy $(TargetPath) C:\Users\scott.TOWEL42\Dropbox\home\bin\EmbyServer\programdata\plugins\" />
        <Exec Command="echo Launching Emby Server" />
        <Exec Command="C:\Users\scott.TOWEL42\Dropbox\home\bin\EmbyServer\system\EmbyServer.exe" />
	</Target>

	<ItemGroup>
		<EmbeddedResource Include="Configuration\movieDVProfileTextPage.html" />
		<EmbeddedResource Include="Configuration\movieDVProfileTextPage.js" />

		<EmbeddedResource Include="Configuration\episodeDVProfileTextPage.html" />
		<EmbeddedResource Include="Configuration\episodeDVProfileTextPage.js" />

		<EmbeddedResource Include="Configuration\movieCodecPage.html" />
		<EmbeddedResource Include="Configuration\movieCodecPage.js" />

		<EmbeddedResource Include="Configuration\movieCodecTextPage.html" />
		<EmbeddedResource Include="Configuration\movieCodecTextPage.js" />

		<EmbeddedResource Include="Configuration\episodeCodecPage.html" />
		<EmbeddedResource Include="Configuration\episodeCodecPage.js" />

		<EmbeddedResource Include="Configuration\episodeCodecTextPage.html" />
		<EmbeddedResource Include="Configuration\episodeCodecTextPage.js" />

		<EmbeddedResource Include="Configuration\PluginConfiguration.cs" />

		<EmbeddedResource Include="Configuration\showOverview.html" />
		<EmbeddedResource Include="Configuration\showOverview.js" />
		
        <EmbeddedResource Include="Configuration\StatisticsConfigPage.html" />
		<EmbeddedResource Include="Configuration\StatisticsConfigPage.js" />
		
        <EmbeddedResource Include="Configuration\userBased.html" />
		<EmbeddedResource Include="Configuration\userBased.js" />
        
		<EmbeddedResource Include="Images\statistics-thumb.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediaBrowser.Server.Core" Version="4.8.11" />
		<PackageReference Include="System.Memory" Version="4.5.5" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>BuildDate</_Parameter1>
			<_Parameter2>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ssK"))</_Parameter2>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
