<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup> 
  <TargetFrameworks>netstandard2.0;</TargetFrameworks> 
  <Version>3.4.2.0</Version> 
  <AssemblyVersion>3.4.2.0</AssemblyVersion> 
  <FileVersion>3.4.2.0</FileVersion>
</PropertyGroup>

<ItemGroup>
  <None Remove="command line.txt" />
  <None Remove="Configuration\moviePage.js" />
  <None Remove="Configuration\movieTextPage.js" />
  <None Remove="Configuration\showOverview.js" />
  <None Remove="Configuration\StatisticsconfigPage.html" />
  <None Remove="Configuration\StatisticsconfigPage.js" />
  <None Remove="Configuration\userBased.js" />
  <None Remove="Images\statistics-thumb.png" />
</ItemGroup>

<ItemGroup>
  <EmbeddedResource Include="Configuration\moviePage.js" />
  <EmbeddedResource Include="Configuration\movieTextPage.js" />
  <EmbeddedResource Include="Configuration\showOverview.js" />
  <EmbeddedResource Include="Configuration\StatisticsConfigPage.html" />
  <EmbeddedResource Include="Configuration\StatisticsConfigPage.js" />
  <EmbeddedResource Include="Configuration\movieTextPage.html" />
  <EmbeddedResource Include="Configuration\moviePage.html" />
  <EmbeddedResource Include="Configuration\showOverview.html" />
  <EmbeddedResource Include="Configuration\userBased.html" />
  <EmbeddedResource Include="Configuration\userBased.js" />
  <EmbeddedResource Include="Images\statistics-thumb.png" />
</ItemGroup>

<ItemGroup>
  <PackageReference Include="MediaBrowser.Server.Core" Version="4.8.11" />
  <PackageReference Include="System.Memory" Version="4.5.5" />
</ItemGroup>

<ItemGroup>
  <Folder Include="Models\Configuration\" />
</ItemGroup>

</Project>
