<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;</TargetFrameworks>
        <Version>1.0.0.0</Version>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
        <LangVersion>9.0</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup>
        <OutputPath>build\$(Configuration)</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <PropertyGroup>
        <InstallAndLaunchPath>$(SolutionDir)\\..\\EmbyPluginUtils\\InstallAndLaunch.bat</InstallAndLaunchPath>
    </PropertyGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent" DependsOnTargets="DetermineEmbyRoot">
        <Exec Command="call $(InstallAndLaunchPath) -Build -TargetPath &quot;$(TargetPath)&quot; -EmbyRoot $(EmbyServerRoot)" />
    </Target>
    
    <PropertyGroup>
        <TargetLaunchDependsOn>$(TargetLaunchDependsOn);DetermineEmbyRoot</TargetLaunchDependsOn>
    </PropertyGroup>
    
    <Target Name="DetermineEmbyRoot" BeforeTargets="BeforeBuild">
        <PropertyGroup Condition="'$(ActiveDebugProfile)' == 'Default'">
            <EmbyServerRoot>$(APPDATA)\Emby-Server</EmbyServerRoot>
        </PropertyGroup>
       
        <PropertyGroup Condition="'$(ActiveDebugProfile)' == 'Small'">
            <EmbyServerRoot>D:\Emby\EmbyServer</EmbyServerRoot>
        </PropertyGroup>

        <PropertyGroup Condition="'$(ActiveDebugProfile)' == 'Full'">
            <EmbyServerRoot>D:\Emby\EmbyServer.full</EmbyServerRoot>
        </PropertyGroup>

        <PropertyGroup Condition="'$(ActiveDebugProfile)' == ''">
            <EmbyServerRoot>###Set Debug Profile###</EmbyServerRoot>
        </PropertyGroup>

        <MakeDir Directories="$(MSBuildProjectDirectory)\.vs\$(ProjectName)\$(Configuration)" />
        <WriteLinesToFile 
            File="$(MSBuildProjectDirectory)/.vs/$(ProjectName)/$(Configuration)/embyroot.cache" 
            Lines="$(EmbyServerRoot)" 
            Overwrite="true" 
            WriteOnlyWhenDifferent="true" />
    </Target>

    <ItemGroup>
        <EmbeddedResource Include="Configuration\PluginConfiguration.cs" />
		<EmbeddedResource Include="Pages\style.css" />
		<EmbeddedResource Include="Pages\Summary.html" />
        <EmbeddedResource Include="Pages\Summary.js" />
        <EmbeddedResource Include="Pages\UserStats.html" />
        <EmbeddedResource Include="Pages\UserStats.js" />
        <EmbeddedResource Include="Pages\TVSeriesProgress.html" />
        <EmbeddedResource Include="Pages\TVSeriesProgress.js" />
        <EmbeddedResource Include="Pages\Movies.html" />
        <EmbeddedResource Include="Pages\Movies.js" />
        <EmbeddedResource Include="Pages\Episodes.html" />
        <EmbeddedResource Include="Pages\Episodes.js" />
        <EmbeddedResource Include="Pages\Settings.html" />
        <EmbeddedResource Include="Pages\Settings.js" />
        <EmbeddedResource Include="Pages\Helpers.js" />
        <EmbeddedResource Include="thumb.png" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Emby.ApiClient" Version="4.8.10" />
        <PackageReference Include="MediaBrowser.Server.Core" Version="4.9.1.90" />
        <PackageReference Include="SQLitePCL.pretty.core" Version="1.2.2" />
        <PackageReference Include="System.Memory" Version="4.6.3" />
    </ItemGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>BuildDate</_Parameter1>
            <_Parameter2>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ssK"))</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
